


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."unidades" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "bloco" "text" NOT NULL,
    "apartamento" smallint NOT NULL,
    "proprietario" json,
    "alugado" boolean,
    "inquilino" json
);


ALTER TABLE "public"."unidades" OWNER TO "postgres";


COMMENT ON TABLE "public"."unidades" IS 'Tabela com as informações dos moradores';



ALTER TABLE "public"."unidades" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."moradores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notificacao" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_tipo_notificacao" bigint NOT NULL,
    "id_unidade" bigint,
    "motivo" "text",
    "categoria" "text",
    "data_retroativa" "date",
    "valor_multa" smallint
);


ALTER TABLE "public"."notificacao" OWNER TO "postgres";


COMMENT ON TABLE "public"."notificacao" IS 'Tabela que será responsável por armazenar as notificações e fará referência a unidade e tipo_notificação.';



ALTER TABLE "public"."notificacao" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notificacao_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tipos_notificacao" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "titulo" "text",
    "texto_regimento" "jsonb"
);


ALTER TABLE "public"."tipos_notificacao" OWNER TO "postgres";


COMMENT ON TABLE "public"."tipos_notificacao" IS 'Essa tabela irá conter os tipos de notificações possíveis: Perturbação de Sossego, Estacionamento Indevido, Comportamento Inadequado, [...]';



ALTER TABLE "public"."tipos_notificacao" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tipos_notificacao_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."unidades"
    ADD CONSTRAINT "moradores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notificacao"
    ADD CONSTRAINT "notificacao_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tipos_notificacao"
    ADD CONSTRAINT "tipos_notificacao_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notificacao"
    ADD CONSTRAINT "notificacao_id_tipo_notificacao_fkey" FOREIGN KEY ("id_tipo_notificacao") REFERENCES "public"."tipos_notificacao"("id");



ALTER TABLE ONLY "public"."notificacao"
    ADD CONSTRAINT "notificacao_id_unidade_fkey" FOREIGN KEY ("id_unidade") REFERENCES "public"."unidades"("id");



CREATE POLICY "All para testes" ON "public"."notificacao" USING (true) WITH CHECK (true);



CREATE POLICY "All para testes" ON "public"."tipos_notificacao" USING (true) WITH CHECK (true);



CREATE POLICY "All para testes" ON "public"."unidades" USING (true) WITH CHECK (true);



ALTER TABLE "public"."notificacao" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tipos_notificacao" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."unidades" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."unidades" TO "anon";
GRANT ALL ON TABLE "public"."unidades" TO "authenticated";
GRANT ALL ON TABLE "public"."unidades" TO "service_role";



GRANT ALL ON TABLE "public"."notificacao" TO "anon";
GRANT ALL ON TABLE "public"."notificacao" TO "authenticated";
GRANT ALL ON TABLE "public"."notificacao" TO "service_role";



GRANT ALL ON TABLE "public"."tipos_notificacao" TO "anon";
GRANT ALL ON TABLE "public"."tipos_notificacao" TO "authenticated";
GRANT ALL ON TABLE "public"."tipos_notificacao" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";







