CREATE UNIQUE INDEX IF NOT EXISTS notificacao_condominio_id_unique_idx
    ON public.notificacao (id_condominio, id);

CREATE TABLE IF NOT EXISTS public.notificacao_anexo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    id_condominio bigint NOT NULL,
    id_notificacao bigint NOT NULL,
    storage_path text NOT NULL UNIQUE,
    nome_arquivo text NOT NULL,
    mime_type text NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp')),
    tamanho_bytes bigint NOT NULL CHECK (tamanho_bytes > 0 AND tamanho_bytes <= 5242880),
    CONSTRAINT notificacao_anexo_notificacao_condominio_fkey
        FOREIGN KEY (id_condominio, id_notificacao)
        REFERENCES public.notificacao (id_condominio, id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS notificacao_anexo_condominio_notificacao_idx
    ON public.notificacao_anexo (id_condominio, id_notificacao, created_at);

ALTER TABLE public.notificacao_anexo ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'notificacao_anexo'
          AND policyname = 'All para testes'
    ) THEN
        EXECUTE $policy$
            CREATE POLICY "All para testes" ON public.notificacao_anexo
                FOR ALL TO anon, authenticated
                USING (true)
                WITH CHECK (true)
        $policy$;
    END IF;
END;
$$;

INSERT INTO storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
VALUES (
    'notificacoes-anexos',
    'notificacoes-anexos',
    false,
    5242880,
    ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE
SET
    public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'storage'
          AND tablename = 'objects'
          AND policyname = 'Anexos de notificações: leitura para testes'
    ) THEN
        EXECUTE $policy$
            CREATE POLICY "Anexos de notificações: leitura para testes"
                ON storage.objects FOR SELECT TO anon, authenticated
                USING (
                    bucket_id = 'notificacoes-anexos'
                    AND (storage.foldername(name))[1] = 'condominios'
                )
        $policy$;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'storage'
          AND tablename = 'objects'
          AND policyname = 'Anexos de notificações: upload para testes'
    ) THEN
        EXECUTE $policy$
            CREATE POLICY "Anexos de notificações: upload para testes"
                ON storage.objects FOR INSERT TO anon, authenticated
                WITH CHECK (
                    bucket_id = 'notificacoes-anexos'
                    AND (storage.foldername(name))[1] = 'condominios'
                )
        $policy$;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'storage'
          AND tablename = 'objects'
          AND policyname = 'Anexos de notificações: remoção para testes'
    ) THEN
        EXECUTE $policy$
            CREATE POLICY "Anexos de notificações: remoção para testes"
                ON storage.objects FOR DELETE TO anon, authenticated
                USING (
                    bucket_id = 'notificacoes-anexos'
                    AND (storage.foldername(name))[1] = 'condominios'
                )
        $policy$;
    END IF;
END;
$$;

GRANT SELECT, INSERT, DELETE ON TABLE public.notificacao_anexo TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.notificacao_anexo_id_seq TO anon, authenticated;
